# Generated by Django 2.1.3 on 2018-12-07 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DiaryBody', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(unique=True)),
                ('Password', models.TextField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='diarytext',
            name='DiaryUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateDiary.DiaryUser'),
        ),
    ]
