# Generated by Django 2.1.3 on 2018-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryuser',
            name='CheckPassword',
            field=models.CharField(default='idiotitissameaspassword', max_length=30),
        ),
        migrations.AlterField(
            model_name='diaryuser',
            name='Password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='diaryuser',
            name='Username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
