# Generated by Django 2.1.3 on 2018-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDiary', '0002_auto_20181210_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='GAGAN SINGH', max_length=30)),
                ('DiaryUser', models.CharField(max_length=30)),
                ('Hobbies', models.TextField(default='Singing', max_length=120)),
                ('LivesAt', models.CharField(default='Delhi', max_length=30)),
                ('Date', models.IntegerField(default='28')),
                ('Month', models.CharField(default='April', max_length=20)),
                ('ProfilePic', models.ImageField(upload_to='UserAvatar')),
            ],
        ),
        migrations.AddField(
            model_name='diarytext',
            name='DiaryHeading',
            field=models.CharField(default="Don't keep it null", max_length=50),
        ),
        migrations.AlterField(
            model_name='diarytext',
            name='DiaryUser',
            field=models.CharField(max_length=30),
        ),
    ]
