# Generated by Django 2.1.3 on 2018-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDiary', '0004_auto_20181216_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Username',
        ),
        migrations.AddField(
            model_name='profile',
            name='WorksAt',
            field=models.CharField(default='ABC', max_length=30),
        ),
        migrations.AlterField(
            model_name='diarytext',
            name='DiaryHeading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Hobbies',
            field=models.TextField(default='empty', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='LivesAt',
            field=models.CharField(default='ABC', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
